SANREMO = {
    "VINCITORE": "Olly",
    "ARTISTS": [
        "Achille Lauro",
        "Gaia Sanremo",
        "Coma_Cose",
        "Francesco Gabbani",
        "Willie Peyote",
        "Noemi Sanremo",
        "Rkomi",
        "Moda Sanremo",
        "Rose Villain",
        "Brunori Sas",
        "Irama",
        "Clara Sanremo",
        "Massimo Ranieri",
        "Sarah Toscano",
        "Fedez",
        "Simone Cristicchi",
        "Joan Thiele",
        "The Kolors",
        "Bresh",
        "Marcella Bella",
        "Tony Effe",
        "Elodie",
        "Olly",
        "Francesca Michielin",
        "Lucio Corsi",
        "Shablo Gue Joshua Tormento",
        "Serena Brancale",
        "Rocco Hunt",
        "Giorgia Sanremo",
    ],
    "NIGHTS": {
        "Prima serata": {
            "data": "2025-02-11",
            "scaletta": [
                "Gaia Sanremo",
                "Francesco Gabbani",
                "Rkomi",
                "Noemi Sanremo",
                "Irama",
                "Coma_Cose",
                "Simone Cristicchi",
                "Marcella Bella",
                "Achille Lauro",
                "Giorgia Sanremo",
                "Willie Peyote",
                "Rose Villain",
                "Olly",
                "Elodie",
                "Shablo Gue Joshua Tormento",
                "Massimo Ranieri",
                "Tony Effe",
                "Serena Brancale",
                "Brunori Sas",
                "Moda Sanremo",
                "Clara Sanremo",
                "Lucio Corsi",
                "Fedez",
                "Bresh",
                "Sarah Toscano",
                "Joan Thiele",
                "Rocco Hunt",
                "Francesca Michielin",
                "The Kolors",
            ],
        },
        "Seconda serata": {
            "data": "2025-02-12",
            "scaletta": [
                "Rocco Hunt",
                "Elodie",
                "Lucio Corsi",
                "The Kolors",
                "Serena Brancale",
                "Fedez",
                "Francesca Michielin",
                "Simone Cristicchi",
                "Marcella Bella",
                "Bresh",
                "Achille Lauro",
                "Giorgia Sanremo",
                "Rkomi",
                "Rose Villain",
                "Willie Peyote",
            ],
        },
        "Terza serata": {
            "data": "2025-02-13",
            "scaletta": [
                "Clara Sanremo",
                "Brunori Sas",
                "Sarah Toscano",
                "Massimo Ranieri",
                "Joan Thiele",
                "Shablo Gue Joshua Tormento",
                "Noemi Sanremo",
                "Olly",
                "Coma_Cose",
                "Moda Sanremo",
                "Tony Effe",
                "Irama",
                "Francesco Gabbani",
                "Gaia Sanremo",
            ],
        },
        "Quarta serata": {
            "data": "2025-02-14",
            "scaletta": [
                "Rose Villain",
                "Moda Sanremo",
                "Clara Sanremo",
                "Noemi Sanremo",
                "Tony Effe",
                "Francesca Michielin",
                "Rkomi",
                "Lucio Corsi",
                "Serena Brancale",
                "Irama",
                "Gaia Sanremo",
                "The Kolors",
                "Marcella Bella",
                "Rocco Hunt",
                "Francesco Gabbani",
                "Giorgia Sanremo",
                "Simone Cristicchi",
                "Sarah Toscano",
                "Coma_Cose",
                "Joan Thiele",
                "Olly",
                "Elodie",
                "Achille Lauro",
                "Massimo Ranieri",
                "Willie Peyote",
                "Brunori Sas",
                "Fedez",
                "Bresh",
                "Shablo Gue Joshua Tormento",
            ],
        },
        "Quinta serata": {
            "data": "2025-02-15",
            "scaletta": [
                "Francesca Michielin",
                "Willie Peyote",
                "Marcella Bella",
                "Bresh",
                "Moda Sanremo",
                "Rose Villain",
                "Tony Effe",
                "Clara Sanremo",
                "Serena Brancale",
                "Brunori Sas",
                "Francesco Gabbani",
                "Noemi Sanremo",
                "Rocco Hunt",
                "The Kolors",
                "Olly",
                "Achille Lauro",
                "Coma_Cose",
                "Giorgia Sanremo",
                "Simone Cristicchi",
                "Elodie",
                "Lucio Corsi",
                "Irama",
                "Fedez",
                "Shablo Gue Joshua Tormento",
                "Joan Thiele",
                "Massimo Ranieri",
                "Gaia Sanremo",
                "Rkomi",
                "Sarah Toscano",
            ],
        },
    },
}
HOUR_RANGES = ["21-22", "22-23", "23-00", "00-01"]
NEXT_DAY_RANGES = ["00-01"]
SERATE = list(SANREMO["NIGHTS"].keys())
SERATE_DATA = {
    serata: SANREMO["NIGHTS"][serata]["data"]
    for serata in SERATE
}